### ISSUE TITLE
Cannot logout the user login

### ISSUE THREAD

**Issue by ashu2490** [aws-samples/aws-saas-factory-eks-reference-architecture#38] opened 2021-08-17 11:55 UTC
After login whenever the logout button is hit it redirects to this URL "https://e2etechnology.com.auth.us-east-1.amazoncognito.com/login?client_id=403oun8l5isf787jlc2v612dtj&response_type=code&redirect_uri=https://admin.e2etechnology.com" and gives a server not found error.
![SasaFactory]

(https://user-images.githubusercontent.com/89002546/129721289-645bb702-0e3b-4ec0-b582-36bfc8af808d.png)

**Comment by ashu2490** [comment] 2021-08-25 04:50
Help us to find out the resolution.

**Comment by akshay27395** [comment] 2021-09-01 04:45
Is any solution for this problem? please help me with the same.

**Comment by tobuck-aws** [comment] 2021-09-22 23:43
Did you figure this out? Are you users of a deployed version of this project? Or developers?

**Comment by tobuck-aws** [comment] 2021-09-30 20:38
Duplicate of #22

**Closed by tobuck-aws** 2021-09-30 20:38 UTC
